### ISSUE TITLE
WFS 'filter - select extent on canvas' : unexpected type 'QgsCoordinateReferenceSystem'

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#58] opened 2018-02-05 14:19 UTC
connected to https://wfspoc.brgm-rec.fr/geoserver/ows
->  choosing Feature type 'ef:EnvironmentalMonitoringFacility'
-> Filter by extent with select extent on canvas that generates that BBOX : 7.51633453933924,8.00596800433564,48.35317290336555,48.804760524798034,EPSG:4326
-> 'Download to': a temporary file or an explicit file path 
-> then 'Download'

: 2018-01-16T10:52:48	WARNING	Traceback (most recent call last):
			  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\load_panel.py", line 213, in on_downloadButton_clicked
			    out = self.download()
			  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\load_panel.py", line 282, in download
			    params['bbox'] = self._get_bbox(wfs)
			  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\load_panel.py", line 251, in _get_bbox
			    transform = QgsCoordinateTransform(self.bboxWidget.crs(), default_crs)
			TypeError: QgsCoordinateTransform(): arguments did not match any overloaded call:
			  overload 1: too many arguments
			  overload 2: not enough arguments
			  overload 3: not enough arguments
			  overload 4: not enough arguments
			  overload 5: argument 1 has unexpected type 'QgsCoordinateReferenceSystem'
			  
			  Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
			  Version de QGIS : 2.99.0-Master Master, b4be39f98b

**Comment by sgrellet** [comment] 2018-03-01 15:27
Tested ok on v1.2.0-rc2 using QGIS 3.0.0-Girona code revision 001c80b0c3

**Comment by sgrellet** [comment] 2018-03-01 15:32
looking at the toolbox logs it seems that, even if the 'Limit to' is unticket the WFS request still contains the count parameter (see below)
 https://wfspoc.brgm-rec.fr:443/geoserver/wfs?service=WFS&version=2.0.0&request=GetFeature&bbox=7.801494357236422,7.507674247425917,48.64987556987084,48.41338621319409,urn:ogc:def:crs:EPSG::4326&typenames=ef:EnvironmentalMonitoringFacility&count=100

**Comment by sgrellet** [comment] 2018-03-05 09:26
Moreover, 
Testing on that WFS 1.1.0 (http://services.sandre.eaufrance.fr/geo/eth_FXX?) with the following BBOX (1.7652995014001838,2.510791612594774,47.66389334744894,48.081820743118634,EPSG:4326), open XML  Mode and 'Load from WFS Layer':
-> I get rivers from the bottom half of France eventhough the BBOX was just around Orléans

**Comment by mhugo** [comment] 2018-04-11 14:54
> looking at the toolbox logs it seems that, even if the 'Limit to' is unticket the WFS request still contains the count parameter (see below)

Fixed now in https://github.com/BRGM/gml_application_schema_toolbox/commit/de58d3e61bbb810459b6a9d00145bcc2d5a8f2d1

**Comment by mhugo** [comment] 2018-04-11 15:06
On BRGM server with the bbox, I can't reproduce the issue, and get the correct result.

On Sandre server, the returned features are indeed wrong. The two servers declare the same default CRS (urn:ogc:def:crs:EPSG::4326). So it seems the problem is server side ?

**Comment by mhugo** [comment] 2018-04-12 07:48
I was wrong, bbox parameters order was wrong, fixed with #57

**Closed by mhugo** 2018-04-12 07:48 UTC
Labels: bug

**Comment by sgrellet** [comment] 2018-04-13 09:35
fixed under 
GMLAS toolbox plugin : v1.2.0-rc4
Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
QGIS : 3.0.1-Girona Girona, a86bec25ebw
