### ISSUE TITLE
Can't transform coordinates, source layer has no

### ISSUE THREAD

**Issue by mhugo** [BRGM/gml_application_schema_toolbox#19] opened 2017-07-11 09:34 UTC
When trying to import 
https://github.com/BRGM/gml_application_schema_toolbox/blob/master/samples/BRGM_raw_database_observation_waterml2_output.xml

Maybe it lacks a way to set the source SRS ...

**Comment by sgrellet** [comment] 2017-07-11 09:36
you already have the SRS 
	<ns:Point xmlns:ns="http://www.opengis.net/gml/3.2" ns:id="Point_mp_BF1FA4BA2438BACF1D9E4515F0B1D676F8EFE891">
							<ns:pos srsName="http://www.opengis.net/def/crs/EPSG/0/4326">49.9506859240222 2.3597603712661</ns:pos>
						</ns:Point>
					</sams:shape>

**Comment by mhugo** [comment] 2017-07-11 09:40
Exact.
There is something else GDAL does not like apparently ...

**Comment by mhugo** [comment] 2017-07-11 16:09
@rouault apparently if 'srcSRS' is not set, the conversion keeps giving me errors and no geometries are created in the sqlite file.
When I set srcSRS to 4326, it works fine.

Example script to reproduce: https://github.com/BRGM/gml_application_schema_toolbox/blob/master/tests/test_load_in_qgis.py#L36

Does that mean the input SRS must be supplied ?

**Comment by rouault** [comment] 2017-07-11 16:20
If you run with gdal.VectorTranlate() with reproject = True and a dstSRS, then the source layers with geometries must have a SRS set, or it must be explictly set with srcSRS

Here the issue is that GDAL doesn't recognize the GML srs as it is set on the pos element (which is valid, but unusual) and not on the Point

Looking if I can come up with a GDAL fix

**Comment by rouault** [comment] 2017-07-11 16:39
Fixed in GDAL per https://trac.osgeo.org/gdal/ticket/6962

**Comment by mhugo** [comment] 2017-07-11 16:41
Thanks !

**Comment by rouault** [comment] 2017-07-11 16:44
Wondering if the combo in the plugin shouldn't have an item that would completely disable reprojection ("Source SRS") ?

**Comment by mhugo** [comment] 2017-07-12 08:17
I've added a 'Source SRS" button in https://github.com/BRGM/gml_application_schema_toolbox/commit/70bbd0fe61da6d18731e8d2e22b6f7dac0c1b1f5

**Closed** 2017-07-12 08:16 UTC
